services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sky-parking-app
    restart: always
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./certificate.crt:/app/certificate.crt
      - ./private.key:/app/private.key
    networks:
      - app-network

  nginx:
    image: nginx:1.24-alpine
    container_name: sky-parking-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge