services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "443:443"
    volumes:
      - ./certificate.crt:/app/certificate.crt
      - ./private.key:/app/private.key