services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./certificate.crt:/app/certificate.crt
      - ./private.key:/app/private.key