version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: sky-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./skyparking.online.key:/etc/nginx/ssl/skyparking.online.key
    depends_on:
      - app
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    container_name: sky-app
    restart: always